---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# r4limnology

<!-- badges: start -->
<!-- badges: end -->

R for Limnology is a workshop geared toward undergraduate and graduate students limnology students using R for the first time. I originally developed some of the included materials for [Indiana University O'Neill School](https://oneill.indiana.edu/) students taking Limnology (E455/E556). You can find an example syllabus of the course [here]().

My goal for this updated workshop is to create more generalized material that applies to *most* limnology courses. Even though I've make this specific for "students", I beleive *anyone* who is interested in learning and using R for limnology and other aquatic disciplines should find a few things useful.

Lastly, this workshop includes many best practices I've learned over the years when teaching anyone R. My hope is that many of the stumbling blocks, unexpected errors, and frustrations with learning a programming language are avoided (or at least reduced). Happy coding! 

## Getting Started

This workshop is compiled as an R *package* that needs to be either installed via GitHub or cloned into a local repository. I have organized the workshop this way because it allows for all the workshop materials, data, and code to be included simply with `library(r4limnology)`. It also allows for the use of [pkgdown]() to generate a website for the workhop, which you can find [here]().

I personally recommend that you *clone* this repository on your local computer. That way you have all the materials available on your own computer while you follow along. Instructions for both methods are found [here]().
 
## Contents

## Have a suggestion?

## License 

r4limnology is licensed under the MIT License. Please see the [LICENSE](LICENSE.md) for more details.

